name: Jobs chain

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Print message and runner os specs
        run: |
          echo "Preparing the environment..."
          echo $RUNNER_OS

  process:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Print current working directory
        run: |
          echo "Processing data..."
          pwd

  finish:
    runs-on: ubuntu-latest
    needs: process
    steps:
      - name: Print finish message
        run: |
          echo "Pipeline complete!"
          echo "Triggered by ${{ github.actor }}"
      